###################
###  WARNING!!! ###
###################
# This file has been autogenerated

# Cython imports
from libcpp.set cimport set as cpp_set
from libcpp.vector cimport vector as cpp_vector
from cython.operator cimport dereference as deref
from cython.operator cimport preincrement as inc
from libc.stdlib cimport malloc, free
from libc.string cimport memcpy
from libcpp.string cimport string as std_string
from libcpp.utility cimport pair
from libcpp.map cimport map as cpp_map
from libcpp.vector cimport vector as cpp_vector
from cpython.version cimport PY_MAJOR_VERSION
from cpython.ref cimport PyTypeObject
from cpython.type cimport PyType_Ready
from cpython.object cimport Py_LT, Py_LE, Py_EQ, Py_NE, Py_GT, Py_GE

# Python Imports
import collections

cimport numpy as np
import numpy as np

np.import_array()

cimport xdress_extra_types

# Cython Imports For Types
cimport xdress_extra_types

# Imports For Types


dtypes = {}

if PY_MAJOR_VERSION >= 3:
    basestring = str


# Dirty ifdef, else, else preprocessor hack
# see http://comments.gmane.org/gmane.comp.python.cython.user/4080
cdef extern from *:
    cdef void emit_ifpy2k "#if PY_MAJOR_VERSION == 2 //" ()
    cdef void emit_ifpy3k "#if PY_MAJOR_VERSION == 3 //" ()
    cdef void emit_else "#else //" ()
    cdef void emit_endif "#endif //" ()

# SetUInt
cdef class _SetIterUInt(object):
    cdef void init(self, cpp_set[xdress_extra_types.uint32] * set_ptr):
        cdef cpp_set[xdress_extra_types.uint32].iterator * itn = <cpp_set[xdress_extra_types.uint32].iterator *> malloc(sizeof(set_ptr.begin()))
        itn[0] = set_ptr.begin()
        self.iter_now = itn

        cdef cpp_set[xdress_extra_types.uint32].iterator * ite = <cpp_set[xdress_extra_types.uint32].iterator *> malloc(sizeof(set_ptr.end()))
        ite[0] = set_ptr.end()
        self.iter_end = ite

    def __dealloc__(self):
        free(self.iter_now)
        free(self.iter_end)

    def __iter__(self):
        return self

    def __next__(self):
        cdef cpp_set[xdress_extra_types.uint32].iterator inow = deref(self.iter_now)
        cdef cpp_set[xdress_extra_types.uint32].iterator iend = deref(self.iter_end)

        if inow != iend:

            pyval = int(deref(inow))
        else:
            raise StopIteration

        inc(deref(self.iter_now))
        return pyval


cdef class _SetUInt:
    def __cinit__(self, new_set=True, bint free_set=True):
        cdef xdress_extra_types.uint32 s


        # Decide how to init set, if at all
        if isinstance(new_set, _SetUInt):
            self.set_ptr = (<_SetUInt> new_set).set_ptr
        elif hasattr(new_set, '__iter__') or \
                (hasattr(new_set, '__len__') and
                hasattr(new_set, '__getitem__')):
            self.set_ptr = new cpp_set[xdress_extra_types.uint32]()
            for value in new_set:

                s = <xdress_extra_types.uint32> long(value)
                self.set_ptr.insert(s)
        elif bool(new_set):
            self.set_ptr = new cpp_set[xdress_extra_types.uint32]()

        # Store free_set
        self._free_set = free_set

    def __dealloc__(self):
        if self._free_set:
            del self.set_ptr

    def __contains__(self, value):
        cdef xdress_extra_types.uint32 s

        if isinstance(value, int):

            s = <xdress_extra_types.uint32> long(value)
        else:
            return False

        if 0 < self.set_ptr.count(s):
            return True
        else:
            return False

    def __len__(self):
        return self.set_ptr.size()

    def __iter__(self):
        cdef _SetIterUInt si = _SetIterUInt()
        si.init(self.set_ptr)
        return si

    def add(self, value):
        cdef xdress_extra_types.uint32 v


        v = <xdress_extra_types.uint32> long(value)
        self.set_ptr.insert(v)
        return

    def discard(self, value):
        cdef xdress_extra_types.uint32 v

        if value in self:

            v = <xdress_extra_types.uint32> long(value)
            self.set_ptr.erase(v)
        return


class SetUInt(_SetUInt, collections.Set):
    """Wrapper class for C++ standard library sets of type <unsigned integer>.
    Provides set like interface on the Python level.

    Parameters
    ----------
    new_set : bool or set-like
        Boolean on whether to make a new set or not, or set-like object
        with values which are castable to the appropriate type.
    free_set : bool
        Flag for whether the pointer to the C++ set should be deallocated
        when the wrapper is dereferenced.

    """
    def __str__(self):
        return self.__repr__()

    def __repr__(self):
        return "set([" + ", ".join([repr(i) for i in self]) + "])"



# double dtype
cdef MemoryKnight[double] mk_double = MemoryKnight[double]()
cdef MemoryKnight[PyXDDouble_Type] mk_double_type = MemoryKnight[PyXDDouble_Type]()

cdef object pyxd_double_getitem(void * data, void * arr):


    pyval = float(deref(<double *> data))
    return pyval

cdef int pyxd_double_setitem(object value, void * data, void * arr):
    cdef double * new_data

    if isinstance(value, float) or isinstance(value, int):

        new_data = mk_double.renew(data)
        new_data[0] = <double> value
        return 0
    else:
        return -1

cdef void pyxd_double_copyswapn(void * dest, np.npy_intp dstride, void * src, np.npy_intp sstride, np.npy_intp n, int swap, void * arr):
    cdef np.npy_intp i
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef double * new_dest

    if src != NULL:
        if (sstride == sizeof(double) and dstride == sizeof(double)):
            new_dest = mk_double.renew(dest)
            new_dest[0] = deref(<double *> src)
        else:
            a = <char *> dest
            b = <char *> src
            for i in range(n):
                new_dest = mk_double.renew(<void *> a)
                new_dest[0] = deref(<double *> b)
                a += dstride
                b += sstride
    if swap: 
        m = sizeof(double) / 2
        a = <char *> dest
        for i in range(n, 0, -1):
            b = a + (sizeof(double) - 1);
            for j in range(m):
                c = a[0]
                a[0] = b[0]
                a += 1
                b[0] = c
                b -= 1
            a += dstride - m

cdef void pyxd_double_copyswap(void * dest, void * src, int swap, void * arr):
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef double * new_dest
    if src != NULL:
        new_dest = mk_double.renew(dest)
        new_dest[0] = (<double *> src)[0]
    if swap:
        m = sizeof(double) / 2
        a = <char *> dest
        b = a + (sizeof(double) - 1);
        for j in range(m):
            c = a[0]
            a[0] = b[0]
            a += 1
            b[0] = c
            b -= 1

cdef np.npy_bool pyxd_double_nonzero(void * data, void * arr):
    return (data != NULL)
    # FIXME comparisons not defined for arbitrary types
    #cdef double zero = double()
    #return ((<double *> data)[0] != zero)

cdef int pyxd_double_compare(const void * d1, const void * d2, void * arr):
    return (d1 == d2) - 1
    # FIXME comparisons not defined for arbitrary types
    #if deref(<double *> d1) == deref(<double *> d2):
    #    return 0
    #else:
    #    return -1

cdef PyArray_ArrFuncs PyXD_Double_ArrFuncs 
PyArray_InitArrFuncs(&PyXD_Double_ArrFuncs)
PyXD_Double_ArrFuncs.getitem = <PyArray_GetItemFunc *> (&pyxd_double_getitem)
PyXD_Double_ArrFuncs.setitem = <PyArray_SetItemFunc *> (&pyxd_double_setitem)
PyXD_Double_ArrFuncs.copyswapn = <PyArray_CopySwapNFunc *> (&pyxd_double_copyswapn)
PyXD_Double_ArrFuncs.copyswap = <PyArray_CopySwapFunc *> (&pyxd_double_copyswap)
PyXD_Double_ArrFuncs.nonzero = <PyArray_NonzeroFunc *> (&pyxd_double_nonzero)
PyXD_Double_ArrFuncs.compare = <PyArray_CompareFunc *> (&pyxd_double_compare)

cdef object pyxd_double_type_alloc(PyTypeObject * self, Py_ssize_t nitems):
    cdef PyXDDouble_Type * cval
    cdef object pyval
    cval = mk_double_type.defnew()
    cval.ob_typ = self
    pyval = <object> cval
    return pyval

cdef void pyxd_double_type_dealloc(object self):
    cdef PyXDDouble_Type * cself = <PyXDDouble_Type *> self
    mk_double_type.deall(cself)
    return

cdef object pyxd_double_type_new(PyTypeObject * subtype, object args, object kwds):
    return pyxd_double_type_alloc(subtype, 0)

cdef void pyxd_double_type_free(void * self):
    return

cdef object pyxd_double_type_str(object self):
    cdef PyXDDouble_Type * cself = <PyXDDouble_Type *> self


    pyval = float((cself.obval))
    s = str(pyval)
    return s

cdef object pyxd_double_type_repr(object self):
    cdef PyXDDouble_Type * cself = <PyXDDouble_Type *> self


    pyval = float((cself.obval))
    s = repr(pyval)
    return s

cdef int pyxd_double_type_compare(object a, object b):
    return (a is b) - 1
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDDouble_Type * x
    #cdef PyXDDouble_Type * y
    #if type(a) is not type(b):
    #    raise NotImplementedError
    #x = <PyXDDouble_Type *> a
    #y = <PyXDDouble_Type *> b
    #if (x.obval == y.obval):
    #    return 0
    #elif (x.obval < y.obval):
    #    return -1
    #elif (x.obval > y.obval):
    #    return 1
    #else:
    #    raise NotImplementedError

cdef object pyxd_double_type_richcompare(object a, object b, int op):
    if op == Py_EQ:
        return (a is b)
    elif op == Py_NE:
        return (a is not b)
    else:
        return NotImplemented
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDDouble_Type * x
    #cdef PyXDDouble_Type * y
    #if type(a) is not type(b):
    #    return NotImplemented
    #x = <PyXDDouble_Type *> a
    #y = <PyXDDouble_Type *> b
    #if op == Py_LT:
    #    return (x.obval < y.obval)
    #elif op == Py_LE:
    #    return (x.obval <= y.obval)
    #elif op == Py_EQ:
    #    return (x.obval == y.obval)
    #elif op == Py_NE:
    #    return (x.obval != y.obval)
    #elif op == Py_GT:
    #    return (x.obval > y.obval)
    #elif op == Py_GE:
    #    return (x.obval >= y.obval)
    #else:
    #    return NotImplemented    

cdef long pyxd_double_type_hash(object self):
    return id(self)

cdef PyMemberDef pyxd_double_type_members[1]
pyxd_double_type_members[0] = PyMemberDef(NULL, 0, 0, 0, NULL)

cdef PyGetSetDef pyxd_double_type_getset[1]
pyxd_double_type_getset[0] = PyGetSetDef(NULL)

cdef bint pyxd_double_is_ready
cdef type PyXD_Double = type("xd_double", ((<object> PyArray_API[10]),), {})
pyxd_double_is_ready = PyType_Ready(<object> PyXD_Double)
(<PyTypeObject *> PyXD_Double).tp_basicsize = sizeof(PyXDDouble_Type)
(<PyTypeObject *> PyXD_Double).tp_itemsize = 0
(<PyTypeObject *> PyXD_Double).tp_doc = "Python scalar type for double"
(<PyTypeObject *> PyXD_Double).tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES | Py_TPFLAGS_HEAPTYPE
(<PyTypeObject *> PyXD_Double).tp_alloc = pyxd_double_type_alloc
(<PyTypeObject *> PyXD_Double).tp_dealloc = pyxd_double_type_dealloc
(<PyTypeObject *> PyXD_Double).tp_new = pyxd_double_type_new
(<PyTypeObject *> PyXD_Double).tp_free = pyxd_double_type_free
(<PyTypeObject *> PyXD_Double).tp_str = pyxd_double_type_str
(<PyTypeObject *> PyXD_Double).tp_repr = pyxd_double_type_repr
(<PyTypeObject *> PyXD_Double).tp_base = (<PyTypeObject *> PyArray_API[10])  # PyGenericArrType_Type
(<PyTypeObject *> PyXD_Double).tp_hash = pyxd_double_type_hash
emit_ifpy2k()
(<PyTypeObject *> PyXD_Double).tp_compare = &pyxd_double_type_compare
emit_endif()
(<PyTypeObject *> PyXD_Double).tp_richcompare = pyxd_double_type_richcompare
(<PyTypeObject *> PyXD_Double).tp_members = pyxd_double_type_members
(<PyTypeObject *> PyXD_Double).tp_getset = pyxd_double_type_getset
pyxd_double_is_ready = PyType_Ready(<object> PyXD_Double)
Py_INCREF(PyXD_Double)
XDDouble = PyXD_Double

cdef PyArray_Descr * c_xd_double_descr = <PyArray_Descr *> malloc(sizeof(PyArray_Descr))
(<PyObject *> c_xd_double_descr).ob_refcnt = 0 # ob_refcnt
(<PyObject *> c_xd_double_descr).ob_type = <PyTypeObject *> PyArray_API[3]
c_xd_double_descr.typeobj = <PyTypeObject *> PyXD_Double # typeobj
c_xd_double_descr.kind = 'x'  # kind, for xdress
c_xd_double_descr.type = 'x'  # type
c_xd_double_descr.byteorder = '='  # byteorder
c_xd_double_descr.flags = 0    # flags
c_xd_double_descr.type_num = 0    # type_num, assigned at registration
c_xd_double_descr.elsize = sizeof(double)  # elsize, 
c_xd_double_descr.alignment = 8  # alignment
c_xd_double_descr.subarray = NULL  # subarray
c_xd_double_descr.fields = NULL  # fields
c_xd_double_descr.names = NULL
(<PyArray_Descr *> c_xd_double_descr).f = <PyArray_ArrFuncs *> &PyXD_Double_ArrFuncs  # f == PyArray_ArrFuncs

cdef object xd_double_descr = <object> (<void *> c_xd_double_descr)
Py_INCREF(<object> xd_double_descr)
xd_double = xd_double_descr
cdef int xd_double_num = PyArray_RegisterDataType(c_xd_double_descr)
dtypes['double'] = xd_double
dtypes['xd_double'] = xd_double
dtypes[xd_double_num] = xd_double



